name: Validation

concurrency:
    group: Validations
    cancel-in-progress: false

on:
  schedule:
    - cron: 30 0/4 * * *
  push:
    paths-ignore:
      - reports/**
      - 'Invalid_Repositories.md'
      - 'invalid_repositories.json'
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'wabbajack-tools/mod-lists'

    steps:
    - uses: actions/checkout@v2

    - name: Set Environment Variables
      if: github.event_name == 'pull_request'
      run: export IS_PULL_REQUEST="True"

    - name: Setup .NET Core SDK 9.0.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    - name: Restore dependencies
      run: dotnet restore Validation/Validation.sln
    - name: Build
      run: dotnet build Validation/Validation.sln --no-restore
    - name: Test
      run: dotnet test Validation/Validation.sln --no-build --verbosity normal

    - name: Sync Validation Output Into Repository
      run: chmod +x sync_validation_output.sh && bash sync_validation_output.sh

    - name: Move Repositories and Log Failing Repositories
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Repository Validation
        repository: mod-lists
        file_pattern: 'Invalid_Repositories.md invalid_repositories.json repositories.json'
